brain:
  - "brain"
  - "cerebrum"
  - "gray matter"
  - "white matter"
  - "cortex"
  - "hippocampus"
  - "amygdala"
  - "frontal cortex"
  - "parietal cortex"
  - "temporal cortex"
  - "occipital cortex"
  - "cerebellum"
  - "brainstem"
  - "medulla oblongata"
  - "thalamus"
  - "hypothalamus"
  - "subthalamus"
  - "midbrain"
  - "pons"
  - "medulla"